from COVID19_vaccine import COVID19Vaccine
import os
from sql_connection_manager import SqlConnectionManager
from vaccine_patient import VaccinePatient
# from vaccine_reservation_scheduler import VaccineReservationScheduler


print(VaccinePatient.patient_a.name)